import React from 'react'
import {Container, Row, Col} from 'react-bootstrap'

function Footer() {
  return (
    <>
        <footer>
            <Container>
                <Col className='text-center'>Template generated by RootAID</Col>
            </Container>
        </footer>
    </>
  )
}

export default Footer